const $=s=>document.querySelector(s),TIME_ACTIVITIES=['Wash','Out','Reach'],COUNT_ACTIVITIES=['Poop','OP'];let charts=[],reportUser=null;
const pad=n=>String(n).padStart(2,'0'),hm=n=>`${pad(Math.floor(n/100))}:${pad(n%100)}`;
function cutoff(range){const d=new Date();if(range==='week')d.setDate(d.getDate()-6);if(range==='month')d.setDate(d.getDate()-29);if(range==='year')d.setFullYear(d.getFullYear()-1);d.setHours(0,0,0,0);return d}
function groupKey(date,range){const d=new Date(date+'T00:00:00');if(range==='year')return date.slice(0,7);return date}
function regression(points){if(points.length<2)return[];const n=points.length,sx=points.reduce((s,p)=>s+p.x,0),sy=points.reduce((s,p)=>s+p.y,0),sxy=points.reduce((s,p)=>s+p.x*p.y,0),sxx=points.reduce((s,p)=>s+p.x*p.x,0),m=(n*sxy-sx*sy)/(n*sxx-sx*sx||1),b=(sy-m*sx)/n;return points.map(p=>({x:p.x,y:m*p.x+b}))}
function mode(a){if(!a.length)return null;const bins={};a.forEach(v=>{const k=Math.round(v/5)*5;bins[k]=(bins[k]||0)+1});return +Object.entries(bins).sort((x,y)=>y[1]-x[1])[0][0]}
function timeStats(rows){const v=rows.map(r=>+r.time.replace(':',''));if(!v.length)return['—','—','—','—'];return[hm(Math.round(v.reduce((a,b)=>a+b,0)/v.length)),hm(Math.min(...v)),hm(Math.max(...v)),hm(mode(v))]}
function countStats(rows){if(!rows.length)return['0','0','0','—'];const by={};rows.forEach(r=>by[r.date]=(by[r.date]||0)+1);const days=Math.max(1,(Date.now()-new Date(rows[0].date+'T00:00:00'))/864e5+1);const high=Object.entries(by).sort((a,b)=>b[1]-a[1])[0];return[rows.length,(rows.length/days).toFixed(2),(rows.length/days*7).toFixed(2),`${high[0]} · ${high[1]}`]}
function card(title,stats,labels){const el=document.createElement('section');el.className='chart-card';el.innerHTML=`<h2>${title}</h2><div class="chart-wrap"><canvas></canvas></div><div class="stats">${stats.map((v,i)=>`<div class="stat">${labels[i]}<b>${v}</b></div>`).join('')}</div>`;$('#charts').append(el);return el.querySelector('canvas')}
async function renderCharts(){if(!reportUser)return;charts.forEach(c=>c.destroy());charts=[];$('#charts').innerHTML='';const range=document.querySelector('[data-range].active').dataset.range,type=$('#chartType').value,all=await ActivityDB.all(reportUser.id),rows=all.filter(r=>new Date(r.timestamp)>=cutoff(range));
if(!rows.length){$('#charts').innerHTML='<div class="empty">No data in this period. Record activities first.</div>';return}
TIME_ACTIVITIES.forEach(a=>{const ar=rows.filter(r=>r.activity===a),pts=ar.map((r,i)=>({x:new Date(r.date+'T'+r.time).getTime(),y:+r.time.replace(':','')}));const canvas=card(a,timeStats(ar),['Average','Earliest','Latest','Common']);const sets=[{label:a,data:pts,borderColor:'#49d3a4',backgroundColor:'#49d3a4',showLine:type==='line',tension:.25,pointRadius:5},{label:'Trend',data:regression(pts),borderColor:'#66a5ff',pointRadius:0,showLine:true,borderDash:[5,5]}];charts.push(new Chart(canvas,{type:'scatter',data:{datasets:sets},options:{responsive:true,maintainAspectRatio:false,scales:{x:{type:'linear',ticks:{callback:v=>new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'})}},y:{min:0,max:2359,ticks:{callback:hm},title:{display:true,text:'Time (HHMM)'}}},plugins:{legend:{labels:{color:'#dce8f7'}}}}}))});
COUNT_ACTIVITIES.forEach(a=>{const ar=rows.filter(r=>r.activity===a),groups={};ar.forEach(r=>{const k=groupKey(r.date,range);groups[k]=(groups[k]||0)+1});const labels=Object.keys(groups).sort(),canvas=card(a,countStats(ar),['Total','Avg/day','Avg/week','Highest day']);charts.push(new Chart(canvas,{type:'bar',data:{labels,datasets:[{label:a,data:labels.map(k=>groups[k]),backgroundColor:a==='Poop'?'#66a5ff':'#ffb86b',borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,ticks:{precision:0},stacked:type==='stacked'},x:{stacked:type==='stacked'}},plugins:{legend:{labels:{color:'#dce8f7'}}}}}))})}
async function applyReportSession(session){reportUser=session?.user||null;$('#authGate').hidden=Boolean(reportUser);$('#reportMain').hidden=!reportUser;$('#appNav').hidden=!reportUser;if(!reportUser)return;if(navigator.onLine){try{await SyncService.sync()}catch(e){console.warn(e)}}await renderCharts()}
async function initReport(){await ActivityDB.open();document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-range]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCharts()});$('#chartType').onchange=renderCharts;document.querySelectorAll('[data-auth-login]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await AuthService.signIn()}catch(e){console.error(e);button.disabled=false}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');AuthService.subscribe(session=>applyReportSession(session).catch(console.error));await applyReportSession(await AuthService.init())}
document.addEventListener('DOMContentLoaded',initReport);
